---
- name: Setup Fedora/Rocky Linux Workstation Environment
  hosts: workstation
  become: true

  pre_tasks:
    - name: Ensure dnf Python bindings are installed
      ansible.builtin.package:
        name: python3-dnf
        state: present

  roles:
    - role: dnf
    - role: system
    - role: cargo
    - role: chezmoi
