---
- name: Copy config.toml
  ansible.builtin.template:
    src: config.toml
    dest: "/home/{{ ansible_user }}/.cargo/config.toml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
