# Automatic security update service
[commands]
upgrade_type = security
download_updates = yes
apply_updates = yes

# Manula reboot is required for changes to take effect
reboot = never
random_sleep = 180

[emitters]
emit_via = stdio

[base]
debuglevel = 1
